#!/bin/bash

IP_ADDRESS=$(hostname -I | awk '{print $1}')

while true; do
    sudo /root/venv/bin/hypercorn --workers 2 --bind "$IP_ADDRESS":6900 --reload main:app
    echo "Command crashed or exited. Restarting in 5 seconds..."
    sleep 5
done